apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-testing-with-node
  labels:
    app: api-testing-with-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-testing-with-node
  template:
    metadata:
      labels:
        app: api-testing-with-node
    spec:
      containers:
      - name: api-testing-with-node
        image: "api-testing-with-node:latest"
        resources:
          requests:
            cpu: 10m